name: Shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  flutter_auth_buttons: ^0.10.0
  provider: ^5.0.0
  firebase_storage: ^8.0.5

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/default.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
